steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '.'
      - '-f'
      - 'Dockerfile'
    id: Build

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - 'run'
      - 'services'
      - 'update'
      - '$_SERVICE_NAME'
      - '--platform=managed'
      - '--image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--port=8080'
      - '--set-env-vars=ASPNETCORE_ENVIRONMENT=Production'
      - '--set-env-vars=DOTNET_RUNNING_IN_CONTAINER=true'
      - '--allow-unauthenticated'
      - '--region=$_DEPLOY_REGION'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--cpu=1'
      - '--memory=512Mi'
      - '--set-cloudsql-instances=${_CLOUDSQL_CONNECTION_NAME}'
      - '--add-cloudsql-instances=${_CLOUDSQL_CONNECTION_NAME}'
      - '--vpc-connector=${_VPC_CONNECTOR}'
      - '--set-secrets=/app/appsettings.secrets.json=sams_secrets:latest'
      - '--labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud

images:
  - '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _SERVICE_NAME: sams
  REPO_NAME: sams
  _TRIGGER_ID: 0dd79c0c-1f74-4240-9b74-5e3440f34dfe
  _DEPLOY_REGION: us-central1
  _CLOUDSQL_CONNECTION_NAME: your-project:your-region:your-instance
  _VPC_CONNECTOR: your-vpc-connector

tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - sams