name: Docker CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/sams-app:latest
        
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOSTNAME: ${{ secrets.EC2_HOST }}
        USER_NAME: ${{ secrets.EC2_USERNAME }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sams-app:latest
          docker stop sams-container || true
          docker rm sams-container || true
          docker run -d -p 5000:5000 \
          -e ConnectionStrings__DefaultConnection="${{ secrets.DB_CONNECTION_STRING }}" \
          -e JWT__ValidAudience="${{ secrets.JWT_VALID_AUDIENCE }}" \
          -e JWT__ValidIssuer="${{ secrets.JWT_VALID_ISSUER }}" \
          -e JWT__Secret="${{ secrets.JWT_SECRET }}" \
          --name sams-container ${{ secrets.DOCKERHUB_USERNAME }}/sams-app:latest
        '